[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''"{{{
let g:deoplete#enable_at_startup = 1
"}}}'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nx = '<Plug>'}
depends = ['vim-repeat']
hook_add = '''"{{{
  nmap _ <Plug>(caw:hatpos:toggle)
  vmap _ <Plug>(caw:hatpos:toggle)
"}}}'''

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'vim-scripts/bnf.vim'
on_ft = 'bnf'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'ymyzk/vim-copl'
on_ft = 'copl'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'ujtakk/vim-verb'
on_ft = 'verb'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp', 'cuda']
hook_source = '''"{{{
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_experimental_template_highlight = 1
  let c_no_curly_error=1
"}}}'''

[[plugins]]
repo = 'petRUShka/vim-opencl'
on_ft = 'opencl'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'chiphogg/vim-prototxt'
on_ft = 'prototxt'

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
hook_source = '''"{{{
  let g:python_highlight_all = 1
"}}}'''

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = 'glsl'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
