[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# depends = ['neomru.vim']
# hook_add = '''"{{{
#   if has('nvim')
#     call denite#custom#option('default', {
#           \ 'prompt': '>',
#           \ 'short_source_names': v:true
#           \ })
#
#     " Change mappings.
#     call denite#custom#map(
#           \ 'insert',
#           \ '<C-j>',
#           \ '<denite:move_to_next_line>',
#           \ 'noremap'
#           \)
#     call denite#custom#map(
#           \ 'insert',
#           \ '<C-k>',
#           \ '<denite:move_to_previous_line>',
#           \ 'noremap'
#           \)
#
#     nnoremap  [Denite] <Nop>
#     nmap      <Space> [Denite]
#
#     " nnoremap <silent> [Denite] :<C-u>Denite file/rec file_mru<CR>
#     nnoremap <silent> [Denite] :<C-u>Denite file/rec<CR>
#   endif
# " }}}'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''"{{{
  " let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#syntastic#enabled = 1
"}}}'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'neomake/neomake'
# hook_add = '''"{{{
#   autocmd! BufWritePost * Neomake
# "}}}'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''"{{{
  let g:ale_sign_error = '⨉'
  let g:ale_sign_warning = '⚠'
"}}}'''

[[plugins]]
repo = 'ujtakk/simplenote.vim'
hook_add = '''"{{{
  " let g:SimplenoteUsername = ""
  " let g:SimplenotePassword = ""
  if filereadable(expand('~/.simplenote_keys'))
    source ~/.simplenote_keys
  endif

  let g:SimplenoteVertical = 1
  let g:SimplenoteListSize = 40
  let g:SimplenoteSingleWindow = 1
  " let g:SimplenoteNoteFormat="[%D] %N%>%T"
  let g:SimplenoteNoteFormat="%N [%T] [%D]"
  let g:SimplenoteStrftime="%Y/%m/%d-%T"
  let g:SimplenoteSortOrder="pinned,title,tags"
  let g:SimplenoteFiletype="markdown"
"}}}'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'tyru/caw.vim'
# on_map = {nx = '<Plug>'}
depends = ['vim-repeat']
hook_add = '''"{{{
  nmap _ <Plug>(caw:hatpos:toggle)
  vmap _ <Plug>(caw:hatpos:toggle)
"}}}'''
